### PR TITLE
Add some 3.5 maps

### PR DESCRIPTION
**Pull request by ghost**
yes

### CODE REVIEW

**Comment by Remint32** [comment]
yes

**Comment by ghost** [comment]
oil rush apparently has no core

**Comment by ghost** [comment]
merge when

**Comment by Remint32** [comment]
> 
> 
> oil rush apparently has no core

is this a problem?

**Comment by Remint32** [comment]
@ritzip 
изображение

**Review by Remint32 — CHANGES_REQUESTED** [review]
@ritzip 
изображение
This needs to be fixed. There are no cores or landing points on the map.

**Review by Remint32 — CHANGES_REQUESTED** [review]
It also seems to me that we need to replace pine trees and holostone.

**Comment by ghost** [comment]
ah, forgot this pr existed

**Comment by ghost** [comment]
@BasedUser ready for merge

**Comment by BasedUser** [comment]
thanks @Remint32

**Pull request merged**
